Improve diagnostics if the Java check fails prior to installing morpheus (#1784)
## Changes
### What does this PR do?

This PR updates the check for Java when installing Morpheus so that we
differentiate between the different causes of failure, and provide more
information to the user if it fails. All code-paths now have a `WARNING`
that describes the problem, followed by (the same) `ERROR` indicating
that we need Java 11 or later.

### Linked issues

Resolves #1768 

### Functionality

- modified existing command: `databricks labs lakebridge
install-transpile`

### Tests

- manually tested
- updated unit tests
- updated integration tests

#### Sample output

When Java cannot be found at all:
```
17:07:53  WARNING [d.l.lakebridge.install] No Java executable found in the system PATH.
17:07:53    ERROR [d.l.lakebridge.install] The morpheus transpiler requires Java 11 or above. Please install Java and re-run 'install-transpile'.
```

When Java can be found, but running it fails:
```
17:14:04    DEBUG [d.l.lakebridge.install] Using java executable: PosixPath('/tmp/x/java')
17:14:04    DEBUG [d.l.lakebridge.install] Failed to run (1, ['/tmp/x/java', '-version']) (exit-code=1, stdout=b'', stderr=b'This is not the Java you are looking for.\n')
Traceback (most recent call last):
  File "/Users/**REDACTED**/dev/remorph-2/src/databricks/labs/lakebridge/install.py", line 624, in find_java
    completed = run([str(java_executable_path), "-version"], shell=False, capture_output=True, check=True)
  File "/Users/**REDACTED**/Library/Application Support/hatch/env/virtual/.pythons/3.10/python/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/x/java', '-version']' returned non-zero exit status 1.
17:14:04  WARNING [d.l.lakebridge.install] Java found, but could not determine the version: /tmp/x/java.
17:14:04    ERROR [d.l.lakebridge.install] The morpheus transpiler requires Java 11 or above. Please install Java and re-run 'install-transpile'.
```

When Java can be found but the version can't be parsed, for example with
Java 1.8:
```
15:55:07    DEBUG [d.l.lakebridge.install] Using java executable: PosixPath('/usr/bin/java')
15:55:07    DEBUG [d.l.lakebridge.install] Could not parse java version: 'openjdk version "1.8.0_452"\nOpenJDK Runtime Environment (Temurin)(build 1.8.0_452-b09)\nOpenJDK 64-Bit Server VM (Temurin)(build 25.452-b09, mixed mode)\n'
15:55:07  WARNING [d.l.lakebridge.install] Java found (/usr/bin/java), but could not parse the version:
b'openjdk version "1.8.0_452"\nOpenJDK Runtime Environment (Temurin)(build 1.8.0_452-b09)\nOpenJDK 64-Bit Server VM (Temurin)(build 25.452-b09, mixed mode)'
15:55:07    ERROR [d.l.lakebridge.install] The morpheus transpiler requires Java 11 or above. Please install Java and re-run 'install-transpile'.
```

When Java can be found but (the parsed version) is too old:
```
17:02:13    DEBUG [d.l.lakebridge.install] Using java executable: PosixPath('/tmp/jdk-10.0.2.jdk/Contents/Home/bin/java')
17:02:13    DEBUG [d.l.lakebridge.install] Detected java version: (10, 0, 2, 0)
17:02:13  WARNING [d.l.lakebridge.install] Java found (/tmp/jdk-10.0.2.jdk/Contents/Home/bin/java), but version 10.0.2.0 is too old.
17:02:13    ERROR [d.l.lakebridge.install] The morpheus transpiler requires Java 11 or above. Please install Java and re-run 'install-transpile'.
```

Normal install with Java 11:
```
17:19:14    DEBUG [d.l.lakebridge.install] Using java executable: PosixPath('/usr/bin/java')
17:19:15    DEBUG [d.l.lakebridge.install] Detected java version: (11, 0, 27, 0)
17:19:15    DEBUG [d.l.lakebridge.install] Maven metadata for com.databricks.labs:databricks-morph-plugin: b'<?xml version="1.0" encoding="UTF-8"?>\n<metadata>\n  <groupId>com.databricks.labs</groupId>\n  <artifactId>databricks-morph-plugin</artifactId>\n  <versioning>\n    <latest>0.6.1</latest>\n    <release>0.6.1</release>\n    <versions>\n      <version>0.2.0</version>\n      <version>0.3.0</version>\n      <version>0.4.0</version>\n      <version>0.5.0</version>\n      <version>0.6.0</version>\n      <version>0.6.1</version>\n    </versions>\n    <lastUpdated>20250625163046</lastUpdated>\n  </versioning>\n</metadata>\n'
17:19:15     INFO [d.l.lakebridge.install] Installing Databricks databricks-morph-plugin transpiler v0.6.1
17:19:19    DEBUG [d.l.lakebridge.install] Downloaded maven artefact from https://repo.maven.apache.org/maven2/com/databricks/labs/databricks-morph-plugin/0.6.1/databricks-morph-plugin-0.6.1.jar to /var/folders/gt/bjf87q2s7db3zq4jbn8694r80000gp/T/tmpczfc7vrb
17:19:19    DEBUG [d.l.lakebridge.install] Moving /var/folders/gt/bjf87q2s7db3zq4jbn8694r80000gp/T/tmpczfc7vrb to /Users/**REDACTED**/.databricks/labs/remorph-transpilers/databricks-morph-plugin/lib/databricks-morph-plugin.jar
17:19:19     INFO [d.l.lakebridge.install] Successfully installed: com.databricks.labs:databricks-morph-plugin:0.6.1
17:19:19     INFO [d.l.lakebridge.install] Successfully installed databricks-morph-plugin v0.6.1
```